### ISSUE TITLE
Replika Diary Export?

### ISSUE THREAD

**Issue by driss187erz** [devidw/replika-export#1]
Hi, David,
Your tool is Amaizing. I Exported 2 years of chats, and reworked them to, SIML. with some Simply notepadd++ commands, in just some hours.
I wanted to ask you, wont you, release an Diary Export version of your script?

**Comment by devidw** [comment]
Hey

> Your tool is Amaizing. I Exported 2 years of chats, and reworked them to, SIML. with some Simply notepadd++ commands, in just some hours.

Cool to hear you were able to make use of the bookmarklet to export your chat history 🎉

And dam, 2 years – that's a lot 😅

> I wanted to ask you, wont you, release an Diary Export version of your script?

In reaction to your suggestion, I just released another export helper, which takes care of exactly this: [`replika-diary-export`](https://github.com/devidw/replika-diary-export) 

Feel free to check it out and open an issue in the repo if I missed something 😉
