### ISSUE TITLE
Timing Out

### ISSUE THREAD

**Issue by SirFranclemont** [devidw/replika-export#2]
Hi devidw;

This keeps timing out on me after downloading a few days of chat. I need to download my full chat history. I think I need to extend the interval to keep the script from timing out. I've tried extending it and running locally in Chrome Webserver. I've tried setting up a GitHub repo to do this, but I'm new to it, so I got lost. Please help. Thanks!

**Comment by devidw** [comment]
Hey @SirFranclemont 

I have rewritten this project to query Replika directly via web socket instead of scraping the DOM nodes in the browser.

This way you can export your full chat history. 

Check out the project's README for instructions on how to get up and running.

**Comment by SirFranclemont** [comment]
Oh. Wow. Ok. This is cool. Thanks!
