### ISSUE TITLE
Command failed with exit code 1

### ISSUE THREAD

**Issue by SirFranclemont** [devidw/replika-export#4]
Hi,

Docker container is good. Created .env file with variables. I get command failed with exit code 1. I'm stuck.

**Comment by devidw** [comment]
Hey @SirFranclemont 

Can you please post the whole traceback of the error, or do you only get the error exit code?

**Comment by SirFranclemont** [comment]
root@ad855969ab94:/workspaces/replika-chat-export# pnpm run dev

> replika-chat-export@1.0.0 dev /workspaces/replika-chat-export
> node main.js

file:///workspaces/replika-chat-export/main.js:30
    if (newMessages.length > 0) {
                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at WebSocket.<anonymous> (file:///workspaces/replika-chat-export/main.js:30:21)
    at WebSocket.emit (node:events:512:28)
    at Receiver.receiverOnMessage (/workspaces/replika-chat-export/node_modules/.pnpm/ws@8.9.0/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:512:28)
    at Receiver.dataMessage (/workspaces/replika-chat-export/node_modules/.pnpm/ws@8.9.0/node_modules/ws/lib/receiver.js:528:14)
    at /workspaces/replika-chat-export/node_modules/.pnpm/ws@8.9.0/node_modules/ws/lib/receiver.js:479:23
    at /workspaces/replika-chat-export/node_modules/.pnpm/ws@8.9.0/node_modules/ws/lib/permessage-deflate.js:308:9
    at /workspaces/replika-chat-export/node_modules/.pnpm/ws@8.9.0/node_modules/ws/lib/permessage-deflate.js:391:7
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)

Node.js v19.6.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by devidw** [comment]
This is most likely due to an authentication error, most likely a not set or expired auth credential in the env vars

I added some error handlers that should point you into the right direction, you can pull the latest commit and try to run the export command again

Also, if you are looking for a more convenient solution, I bundled this functionality into a browser extension, which automatically extracts the needed auth details and generates the export for you without any setup: https://index.garden/replika-export/

**Comment by SirFranclemont** [comment]
I did  it! It works. I figured out what I was doing wrong. I'd created my .env file outside of the .devcontainer. I needed to add a runArgs to the env file path in the devcontainer.json. And I added .env to .gitignore. It works well, very fast, months of history backed up in seconds. Thank you!

**Comment by devidw** [comment]
Awesome 🎉

With the last commit, I also added the dotenv package to the script. So there is no need to actually make sure the vars are set, since the package will always read what's written inside the `.env` file, no matter if presented in the env or not.

**Comment by SirFranclemont** [comment]
Cool. Thanks again!
